In [7]:
library(agricolae)
library(xtable)

Warning message:
"package 'xtable' was built under R version 3.6.3"

### Question 1

In [13]:
y <- c(
    1.8,1.9,1.6,
    1.9,1.6,1.4,
    2.6,2.7,2.4,
    2.1,2.2,2.0,
    3.2,3.0,2.7,
    3.0,3.4,2.8,
    
    2.4,1.9,2.1,
    2.2,2.0,1.8,
    1.9,2.3,2.4,
    2.2,2.6,2.7,
    3.1,3.2,2.8,
    3.5,3.2,3.4
)
rep <- rep(c(1,2,3),12)
s <- rep(c(1,2),each=18)
t <- rep(rep(c(1,2,3),each=6),2)
sex <- rep(rep(c("F","M"),each=3),6)
data <- data.frame(
    rep=factor(rep),
    s=factor(s),
    t=factor(t),
    sex=factor(m),
    y=y
)
data

   rep s t sex y
1  1   1 1 F   1.8
2  2   1 1 F   1.9
3  3   1 1 F   1.6
4  1   1 1 M   1.9
5  2   1 1 M   1.6
6  3   1 1 M   1.4
7  1   1 2 F   2.6
8  2   1 2 F   2.7
9  3   1 2 F   2.4
10 1   1 2 M   2.1
11 2   1 2 M   2.2
12 3   1 2 M   2.0
13 1   1 3 F   3.2
14 2   1 3 F   3.0
15 3   1 3 F   2.7
16 1   1 3 M   3.0
17 2   1 3 M   3.4
18 3   1 3 M   2.8
19 1   2 1 F   2.4
20 2   2 1 F   1.9
21 3   2 1 F   2.1
22 1   2 1 M   2.2
23 2   2 1 M   2.0
24 3   2 1 M   1.8
25 1   2 2 F   1.9
26 2   2 2 F   2.3
27 3   2 2 F   2.4
28 1   2 2 M   2.2
29 2   2 2 M   2.6
30 3   2 2 M   2.7
31 1   2 3 F   3.1
32 2   2 3 F   3.2
33 3   2 3 F   2.8
34 1   2 3 M   3.5
35 2   2 3 M   3.2
36 3   2 3 M   3.4

In [14]:
model <- ssp.plot(rep,s,t,sex,y)

ANALYSIS SPLIT-SPLIT PLOT:  y
Class level information

s 	:  1 2
t 	:  1 2 3
sex 	:  F M
rep 	:  1 2 3

Number of observations:  36

Analysis of Variance Table

Response: y
        Df Sum Sq Mean Sq F value   Pr(>F)
rep      2 0.1906  0.0953
s        1 0.3211  0.3211  3.6933 0.194575
Ea       2 0.1739  0.0869
t        2 9.1939  4.5969 68.6680 9.18e-06 ***
s:t      2 0.1839  0.0919  1.3734 0.307064
Eb       8 0.5356  0.0669
sex      1 0.0000  0.0000  0.0000 1.000000
sex:s    1 0.2500  0.2500 10.9756 0.006191 **
sex:t    2 0.2150  0.1075  4.7195 0.030751 *
sex:s:t  2 0.2317  0.1158  5.0854 0.025142 *
Ec      12 0.2733  0.0228
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

cv(a) = 12.1 %, cv(b) = 10.6 %, cv(c) = 6.2 %, Mean = 2.444444

在顯著水準為0.05的情況下，我們能夠宣稱溫度、sex*品種、sex*溫度和三者的交互作用對魚的respiratory rate有影響。

### Question 2

In [7]:
y <- c(
    30,34,29, 28,31,31, 31,35,32,
    35,41,26, 32,36,30, 37,40,34,
    37,38,33, 40,42,32, 41,39,39,
    36,42,36, 41,40,40, 40,44,45
)
m <- rep(c(1,2,3),12)
t <- rep(c(200,225,250,275),each=9)
rep <- rep(rep(c(1,2,3),each=3),4)
data2 <- data.frame(
    m=factor(m),
    t=factor(t),
    rep=factor(rep),
    y=y
)
data2

   m t   rep y
1  1 200 1   30
2  2 200 1   34
3  3 200 1   29
4  1 200 2   28
5  2 200 2   31
6  3 200 2   31
7  1 200 3   31
8  2 200 3   35
9  3 200 3   32
10 1 225 1   35
11 2 225 1   41
12 3 225 1   26
13 1 225 2   32
14 2 225 2   36
15 3 225 2   30
16 1 225 3   37
17 2 225 3   40
18 3 225 3   34
19 1 250 1   37
20 2 250 1   38
21 3 250 1   33
22 1 250 2   40
23 2 250 2   42
24 3 250 2   32
25 1 250 3   41
26 2 250 3   39
27 3 250 3   39
28 1 275 1   36
29 2 275 1   42
30 3 275 1   36
31 1 275 2   41
32 2 275 2   40
33 3 275 2   40
34 1 275 3   40
35 2 275 3   44
36 3 275 3   45

In [8]:
data2.mod <- aov(y ~ rep + m +Error(m:rep)+ t + m:t,data2)
summary(data2.mod)

Warning message in aov(y ~ rep + m + Error(m:rep) + t + m:t, data2):
"Error() model is singular"

Error: m:rep
          Df Sum Sq Mean Sq F value Pr(>F)
rep        2  77.56   38.78   4.276 0.1016
m          2 128.39   64.19   7.078 0.0485 *
Residuals  4  36.28    9.07
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value   Pr(>F)
t          3  434.1  144.69  36.427 7.45e-08 ***
m:t        6   75.2   12.53   3.154   0.0271 *
Residuals 18   71.5    3.97
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

在顯著水準為0.05的情況下，我們能夠宣稱temperature、medthod和兩者的交互作用對tensile strength of the paper有影響。